/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package fr.insa.tc.RTC;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-05-09")
public class UpdateData implements org.apache.thrift.TBase<UpdateData, UpdateData._Fields>, java.io.Serializable, Cloneable, Comparable<UpdateData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UpdateData");

  private static final org.apache.thrift.protocol.TField FILE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("FileName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField FILE_FIELD_DESC = new org.apache.thrift.protocol.TField("File", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new UpdateDataStandardSchemeFactory());
    schemes.put(TupleScheme.class, new UpdateDataTupleSchemeFactory());
  }

  public String FileName; // required
  public ByteBuffer File; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FILE_NAME((short)1, "FileName"),
    FILE((short)2, "File");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FILE_NAME
          return FILE_NAME;
        case 2: // FILE
          return FILE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FILE_NAME, new org.apache.thrift.meta_data.FieldMetaData("FileName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.FILE, new org.apache.thrift.meta_data.FieldMetaData("File", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UpdateData.class, metaDataMap);
  }

  public UpdateData() {
  }

  public UpdateData(
    String FileName,
    ByteBuffer File)
  {
    this();
    this.FileName = FileName;
    this.File = org.apache.thrift.TBaseHelper.copyBinary(File);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UpdateData(UpdateData other) {
    if (other.isSetFileName()) {
      this.FileName = other.FileName;
    }
    if (other.isSetFile()) {
      this.File = org.apache.thrift.TBaseHelper.copyBinary(other.File);
    }
  }

  public UpdateData deepCopy() {
    return new UpdateData(this);
  }

  @Override
  public void clear() {
    this.FileName = null;
    this.File = null;
  }

  public String getFileName() {
    return this.FileName;
  }

  public UpdateData setFileName(String FileName) {
    this.FileName = FileName;
    return this;
  }

  public void unsetFileName() {
    this.FileName = null;
  }

  /** Returns true if field FileName is set (has been assigned a value) and false otherwise */
  public boolean isSetFileName() {
    return this.FileName != null;
  }

  public void setFileNameIsSet(boolean value) {
    if (!value) {
      this.FileName = null;
    }
  }

  public byte[] getFile() {
    setFile(org.apache.thrift.TBaseHelper.rightSize(File));
    return File == null ? null : File.array();
  }

  public ByteBuffer bufferForFile() {
    return org.apache.thrift.TBaseHelper.copyBinary(File);
  }

  public UpdateData setFile(byte[] File) {
    this.File = File == null ? (ByteBuffer)null : ByteBuffer.wrap(Arrays.copyOf(File, File.length));
    return this;
  }

  public UpdateData setFile(ByteBuffer File) {
    this.File = org.apache.thrift.TBaseHelper.copyBinary(File);
    return this;
  }

  public void unsetFile() {
    this.File = null;
  }

  /** Returns true if field File is set (has been assigned a value) and false otherwise */
  public boolean isSetFile() {
    return this.File != null;
  }

  public void setFileIsSet(boolean value) {
    if (!value) {
      this.File = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case FILE_NAME:
      if (value == null) {
        unsetFileName();
      } else {
        setFileName((String)value);
      }
      break;

    case FILE:
      if (value == null) {
        unsetFile();
      } else {
        setFile((ByteBuffer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case FILE_NAME:
      return getFileName();

    case FILE:
      return getFile();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case FILE_NAME:
      return isSetFileName();
    case FILE:
      return isSetFile();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof UpdateData)
      return this.equals((UpdateData)that);
    return false;
  }

  public boolean equals(UpdateData that) {
    if (that == null)
      return false;

    boolean this_present_FileName = true && this.isSetFileName();
    boolean that_present_FileName = true && that.isSetFileName();
    if (this_present_FileName || that_present_FileName) {
      if (!(this_present_FileName && that_present_FileName))
        return false;
      if (!this.FileName.equals(that.FileName))
        return false;
    }

    boolean this_present_File = true && this.isSetFile();
    boolean that_present_File = true && that.isSetFile();
    if (this_present_File || that_present_File) {
      if (!(this_present_File && that_present_File))
        return false;
      if (!this.File.equals(that.File))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_FileName = true && (isSetFileName());
    list.add(present_FileName);
    if (present_FileName)
      list.add(FileName);

    boolean present_File = true && (isSetFile());
    list.add(present_File);
    if (present_File)
      list.add(File);

    return list.hashCode();
  }

  @Override
  public int compareTo(UpdateData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetFileName()).compareTo(other.isSetFileName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFileName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.FileName, other.FileName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFile()).compareTo(other.isSetFile());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFile()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.File, other.File);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("UpdateData(");
    boolean first = true;

    sb.append("FileName:");
    if (this.FileName == null) {
      sb.append("null");
    } else {
      sb.append(this.FileName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("File:");
    if (this.File == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.File, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UpdateDataStandardSchemeFactory implements SchemeFactory {
    public UpdateDataStandardScheme getScheme() {
      return new UpdateDataStandardScheme();
    }
  }

  private static class UpdateDataStandardScheme extends StandardScheme<UpdateData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, UpdateData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // FILE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.FileName = iprot.readString();
              struct.setFileNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FILE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.File = iprot.readBinary();
              struct.setFileIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, UpdateData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.FileName != null) {
        oprot.writeFieldBegin(FILE_NAME_FIELD_DESC);
        oprot.writeString(struct.FileName);
        oprot.writeFieldEnd();
      }
      if (struct.File != null) {
        oprot.writeFieldBegin(FILE_FIELD_DESC);
        oprot.writeBinary(struct.File);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UpdateDataTupleSchemeFactory implements SchemeFactory {
    public UpdateDataTupleScheme getScheme() {
      return new UpdateDataTupleScheme();
    }
  }

  private static class UpdateDataTupleScheme extends TupleScheme<UpdateData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UpdateData struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetFileName()) {
        optionals.set(0);
      }
      if (struct.isSetFile()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetFileName()) {
        oprot.writeString(struct.FileName);
      }
      if (struct.isSetFile()) {
        oprot.writeBinary(struct.File);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UpdateData struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.FileName = iprot.readString();
        struct.setFileNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.File = iprot.readBinary();
        struct.setFileIsSet(true);
      }
    }
  }

}

